#include "df3d_pch.h"

const char *ConsoleRml = "<div>\n"
    "<div id=\"previous_commands\"></div>\n"
    "<div>\n"
    "    <p>==></p>\n"
    "</div>\n"
    "<div>\n"
    "    <input type=\"text\" id=\"console_input\"></input>\n"
    "</div>\n"
    "<div>\n"
    "    <button id=\"submit_command\">Submit</button>\n"
    "</div>\n"
    "</div>\n"
;

const char *ConsoleRcss = "body\n"
"{\n"
"    z-index: top;\n"
"    font-family: Lacuna;\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"    position: absolute;\n"
"    font-size: 15;\n"
"    color: black;\n"
"    background-color: #8887;\n"
"    left: 20px;\n"
"    top: 50px;\n"
"}\n"
"\n"
"div\n"
"{\n"
"    display: block;\n"
"    margin-top: 4px;\n"
"    margin-bottom: 4px;\n"
"    margin-left: 4px;\n"
"}\n"
"\n"
"p\n"
"{\n"
"    font-size: 12;\n"
"}\n"
"\n"
"input.text\n"
"{\n"
"    background-color: #888;\n"
"}\n"
"\n"
"button\n"
"{\n"
"    border-width: 1px;\n"
"    border-color: #666;\n"
"    background: #ddd;\n"
"    margin-left: 6px;\n"
"    display: inline-block;\n"
"    width: 100px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"button:hover\n"
"{\n"
"    background: #eee;\n"
"}\n"
"\n"
"div#previous_commands\n"
"{\n"
"    white-space: pre;\n"
"    height: 300px\n"
"    max-height: 300px;\n"
"    overflow: hidden auto;\n"
"}\n"
"\n"
"scrollbarvertical\n"
"{\n"
"   width: 16px;\n"
"   scrollbar-margin: 16px;\n"
"}\n"
"\n"
"scrollbarhorizontal\n"
"{\n"
"   height: 16px;\n"
"   scrollbar-margin: 16px;\n"
"}\n"
"\n"
"scrollbarvertical slidertrack,\n"
"scrollbarhorizontal slidertrack\n"
"{\n"
"   background: #aaa;\n"
"   border-color: #888;\n"
"}\n"
"\n"
"scrollbarvertical slidertrack\n"
"{\n"
"   border-left-width: 1px;\n"
"}\n"
"\n"
"scrollbarhorizontal slidertrack\n"
"{\n"
"   height: 15px;\n"
"   border-top-width: 1px;\n"
"}\n"
"\n"
"scrollbarvertical sliderbar,\n"
"scrollbarhorizontal sliderbar\n"
"{\n"
"   background: #ddd;\n"
"   border-color: #888;\n"
"}\n"
"\n"
"scrollbarvertical sliderbar\n"
"{\n"
"   border-width: 1px 0px;\n"
"   margin-left: 1px;\n"
"}\n"
"\n"
"scrollbarhorizontal sliderbar\n"
"{\n"
"   height: 15px;\n"
"   border-width: 0px 1px;\n"
"   margin-top: 1px;\n"
"}\n"
"\n"
"scrollbarcorner\n"
"{\n"
"   background: #888;\n"
"}\n"
;
